# Site settings
title: FOAM Framework
description: "FOAM is a deeply MVC Javascript framework"
baseurl: "https://foam-framework.github.io/foam"
url: "https://foam-framework.github.io/foam"

# Build settings
markdown: kramdown
permalink: pretty
