var files = [
  'stdlib',
  'io',
  'writer',
  'socket',
  'hash',
  'base64',
  'utf8',
  'parse',
//  'scaleParser',
  'context',
//  'context2',
  'event',
  'SimpleValue',
  'JSONUtil',
  'XMLUtil',
  'FOAM',
  'TemplateUtil',
  'AbstractPrototype',
  'ModelProto',
  'mm1Model',
  'mm2Property',
  'mm3Types',
  'mm4Method',
  'mm5Misc',
  'view',
  'RichTextView',
  'listchoiceview',
  'scroll',
  'mlang',
  'QueryParser',
  'search',
  'async',
//  'async_test',
  'visitor',
  'dao',
  'diff',
  'SplitDAO',
  'index',
  'StackView',
  'DAOController',
  'ThreePaneController',
  'experimental/protobufparser',
  'experimental/protobuf',
  // remove below here
  'models',
  'glang',
  'demos/demos',
  'oauth',
  'apps/tomail/view',
  'apps/tomail/email',
  'turntable'
];
