/**
 * @license
 * Copyright 2015 Google Inc. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

CLASS({
  package: 'foam.util',
  name: 'JavaSource2',
  requires: [
    'foam.i18n.TranslationFormatStringParser',
    'foam.util.InlineTrait',
  ],

  methods: [
    function prepModel(model) {
      // Java doesn't support traits, so we'll copy traits into the model directly.
      model = this.InlineTrait.create().inlineTraits(model);

      var filter = function(m) {
        if ( m.labels && m.labels.indexOf('java') == -1 ) {
          return false;
        }
        return true;
      };

      model.properties = model.properties.filter(filter);
      model.methods = model.methods.filter(filter);
      model.listeners = model.listeners.filter(filter);

      return model;
    },
    function generate(model) {
      if ( model.javaSource ) {
        return model.javaSource();
      }
      return this.javaSource.call(this.prepModel(model), undefined, this);
    },
  ],

  templates: [
    function javaSource(_, util) {/*<%
var propertyMap = {}
var toPropertyMap = function(f) {
  propertyMap[f.name] = f;
}
this.properties.forEach(toPropertyMap);

var idName;
var modelProperties = [];
var overriddenProperties = [];
var runtimeProperties = this.getRuntimeProperties();
var parent = this.X.lookup(this.extends);
for ( var i = 0 ; i < runtimeProperties.length ; i++ ) {
  var prop = runtimeProperties[i];
  if (prop.name == 'id') { idName = prop.name; }
  if (prop.labels && (
    prop.labels.indexOf('compiletime') != -1 ||
    prop.labels.indexOf('java') == -1 ) ) { continue; }
  if (parent && parent.getProperty(prop.name)) {
    if (propertyMap[prop.name]) {
      overriddenProperties.push(prop);
    }
    continue;
  }
  modelProperties.push(prop)
}
var allProperties = modelProperties.concat(overriddenProperties);
if (!idName) {
  if (this.ids && this.ids.length) {
    idName = this.ids[0];
  } else if(allProperties.length) {
    idName = allProperties[0].name;
  }
} else {
  // Since there's already an ID property, we don't need to do any special
  // handling of ID so unset it.
  idName = undefined;
}

var defaultPackage = 'foam.core';

var allRequires = this.getAllRequires();
if (parent) allRequires.push(parent.id);
allRequires = allRequires.map(function(req) {
  if (req && req.indexOf('.') == -1) {
    req = defaultPackage + '.' + req;
  }
  return req;
});

%>
// Generated by foam.util.JavaSource2.  DO NOT MODIFY BY HAND
package <%= this.package || defaultPackage %>;

import foam.core2.*;

<% this.javaClassImports.forEach(function(i) { %>
import <%= i %>;
<% }); %>

<% allRequires.forEach(function(req) { %>
import <%= req %>;
<% }); %>

public class <%= this.javaClassName %> extends <%= parent && parent.javaClassName || 'FObject' %> {

<% for ( var i = 0, message; message = this.messages[i]; i++) { %>
  public static String <%= message.name %> = "<%= message.value %>";
<% } %>

<% for (var i = 0, constant; constant = this.constants[i]; i++) { %>
  <% if (constant.javaValue && constant.javaType) { %>
  public static <%= constant.javaType %> <%= constant.name %> = <%= constant.javaValue %>;
  <% } %>
<% } %>

<%
for ( var i = 0 ; i < allProperties.length ; i++ ) {
  var prop = allProperties[i];
  var override = overriddenProperties.indexOf(prop) != -1 ? 'override' : '';
  var name = prop.name;
  var constant = constantize(name);
  var type = prop.javaType;
  var propertyModel = prop.model_.id.split('.').pop();
  var propFactory = prop.javaFactory || prop.javaLazyFactory;
%>
  <% if (!override) { %>
  protected <%= type %> <%= name %>_;
  protected boolean <%= name %>Inited_ = false;
  <% } %>

  private static <%= propertyModel %> <%= this.javaClassName %>_<%= constant %>_;
  public static <%= propertyModel %> <%= this.javaClassName %>_<%= constant %>() {
    if (<%= this.javaClassName %>_<%= constant %>_ != null)
      return <%= this.javaClassName %>_<%= constant %>_;
    <%= propertyModel %> p = new <%= propertyModel %>();
    p.setName("<%= name %>");
    p.setLabel("<%= prop.label %>");
  <% if (prop.javaValidate) { %>
    p.setValidate(new FoamFunction<String>() {
      @Override public String call(Object... args) {
        <%= this.javaClassName %> fobj = (<%= this.javaClassName %>) args[0];
        return fobj.validate_<%= name %>();
      }
    });
  <% } %>
    <%= propertyModel %> <%= this.javaClassName %>_<%= constant %>_ = p;
    return p;
  }

  <% if (prop.javaValidate) { %>
  public String validate_<%= name %>() {
    <%= type %> value = get<%= name.capitalize() %>();
    <%= propertyModel %> property = <%= this.javaClassName %>_<%= constant %>();
    <%= multiline(prop.javaValidate) %>
  }
  <% } %>

  public <%= type %> get<%= name.capitalize() %>() {
  <% if (prop.javaGetter) { %>
    <%= TemplateUtil.lazyCompile(TemplateUtil.expandTemplate(prop, prop.javaGetter)).bind(prop)() %>
  <% } else { %>
    if (<%= name %>Inited_) {
      return <%= name %>_;
    }
    <% if (prop.javaDefaultValueFn) { %>
    <%= prop.javaDefaultValueFn %>
    <% } else if (prop.javaDefaultValue) { %>
    return <%= prop.javaDefaultValue %>;
    <% } else if (propFactory) { %>
    set<%= name.capitalize() %>(_<%= name %>_factory());
    return <%= prop.name %>_;
    <% } else { %>
    return <%= prop.name %>_;
    <% } %>
  <% } %>
  }

  <% if (propFactory) { %>
  private <%= type %> _<%= name %>_factory() { <%= propFactory %> }
  <% } %>

  private <%= type %> <%= name %>_adapt_(Object oldValue, Object newValue) {
    <%= TemplateUtil.lazyCompile(TemplateUtil.expandTemplate(prop, prop.javaAdapt)).bind(prop)() %>
  }
  protected <%= type %> <%= name %>_adapt(Object oldValue, Object newValue) {
  <% if (override) { %>
    return super.<%= name %>_adapt(oldValue, <%= name %>_adapt_(oldValue, newValue));
  <% } else { %>
    return <%= name %>_adapt_(oldValue, newValue);
  <% } %>
  }

  private <%= type %> <%= name %>_preSet_(Object oldValue, <%= type %> newValue) {
    <%= TemplateUtil.lazyCompile(TemplateUtil.expandTemplate(prop, prop.javaPreSet)).bind(prop)() %>
  }
  protected <%= type %> <%= name %>_preSet(Object oldValue, <%= type %> newValue) {
  <% if (override) { %>
    return super.<%= name %>_preSet(oldValue, <%= name %>_preSet_(oldValue, newValue));
  <% } else { %>
    return <%= name %>_preSet_(oldValue, newValue);
  <% } %>
  }

  private void <%= name %>_postSet_(Object oldValue, <%= type %> newValue) {
    <%= TemplateUtil.lazyCompile(TemplateUtil.expandTemplate(prop, prop.javaPostSet)).bind(prop)() %>
  }
  protected void <%= name %>_postSet(Object oldValue, <%= type %> newValue) {
  <% if (override) { %>
    super.<%= name %>_postSet(oldValue, newValue);
  <% } %>
    <%= name %>_postSet_(oldValue, newValue);
  }

  public void set<%= name.capitalize() %>(<%= type %> value) {
    set("<%= name %>", value);
  }
<% } %>

  // TODO(mcarcaso): Equals and clone shouldn't need to be generated. We should
  // be able to walk the properties at runtime.
  public boolean equals(Object o) {
    if (!(o instanceof <%= this.javaClassName %>)) {
      return false;
    }
    <%= this.javaClassName %> castedO = (<%= this.javaClassName %>) o;
<%
var primitives = [
  'byte',
  'char',
  'short',
  'int',
  'long',
  'float',
  'double',
  'boolean',
];
%>
<% for (var i = 0, prop; prop = allProperties[i]; i++) { %>
  <% var get = 'get' + prop.name.capitalize() + '()'; %>
  <% if (primitives.indexOf(prop.javaType) == -1) { %>
    if (<%= get %> != null) {
      if (!<%= get %>.equals(castedO.<%= get %>)) return false;
    } else if (castedO.<%= get %> != null) {
      return false;
    }
  <% } else { %>
    if (<%= get %> != castedO.<%= get %>) return false;
  <% } %>
<% } %>
    return true;
  }

  public <%= this.javaClassName %> clone() {
    <%= this.javaClassName %> c = new <%= this.javaClassName %>();
<% for (var i = 0, prop; prop = allProperties[i]; i++) { %>
    c.set<%= prop.name.capitalize() %>(get<%= prop.name.capitalize() %>());
<% } %>
    return c;
  }

  public Object get(String key) {
    switch (key) {
<% for (var i = 0, prop; prop = allProperties[i]; i++) { %>
  <% var name = prop.name, type = prop.javaType %>
      case "<%= name %>":
        return get<%= name.capitalize() %>();
<% } %>
      default:
        break;
    }
    return super.get(key);
  }

  public foam.core.Property getProperty(String key) {
    switch (key) {
<% for (var i = 0, prop; prop = allProperties[i]; i++) { %>
  <% var name = prop.name, type = prop.javaType %>
      case "<%= name %>":
        return <%= this.javaClassName %>_<%= constantize(name) %>();
<% } %>
      default:
        break;
    }
    return super.getProperty(key);
  }

  public void set(String key, Object value) {
    switch (key) {
<% for (var i = 0, prop; prop = allProperties[i]; i++) { %>
  <% var name = prop.name, type = prop.javaType %>
      case "<%= name %>":
        <%= type %> <%=name%>Old = <%= name %>_;
        <%= name %>_ = <%= name %>_preSet(<%=name%>Old, <%= name %>_adapt(<%=name%>Old, value));
        <%= name %>Inited_ = true;
        <%= name %>_postSet(<%=name%>Old, <%= name %>_);
        break;
<% } %>
      default:
        super.set(key, value);
        break;
    }
  }

  public void clearProperty(String key) {
    switch (key) {
<% for (var i = 0, prop; prop = allProperties[i]; i++) { %>
  <% var name = prop.name %>
      case "<%= name %>":
        <%= name %>_ = null;
        <%= name %>Inited_ = false;
        break;
<% } %>
      default:
        super.clearProperty(key);
        break;
    }
  }

<%
var staticModelName = this.javaClassName + 'Model_';
var staticModelProperties = modelProperties.map(function(prop) {
  return this.javaClassName + '_' + constantize(prop.name) + '()';
}.bind(this));
%>
private static foam.core.Model <%=staticModelName%>;
public static foam.core.Model <%=this.javaClassName%>Model() {
  if (<%=this.javaClassName%>Model_ == null) {
    java.util.List<foam.core.Property> properties =
        java.util.Arrays.asList(<%=staticModelProperties.join(',')%>);
<% if (parent) { %>
    properties.addAll(
        <%=parent.id%>.<%=parent.javaClassName%>Model().getProperties());
<% } %>
    <%=this.javaClassName%>Model_ = new foam.core.Model();
    <%=this.javaClassName%>Model_.setName("<%= this.javaClassName %>");
    <%=this.javaClassName%>Model_.setProperties(properties);
  }
  return <%=this.javaClassName%>Model_;
}
public foam.core.Model getModel() {
  return <%= this.javaClassName %>Model();
}

<%
  function javaSource(f) {
    f.javaSource$f && f.javaSource$f.call(f, out, self);
  }

  this.methods.forEach(javaSource);
  this.listeners.forEach(javaSource);
  this.actions.forEach(javaSource);
%>

  <%= multiline(this.javaCode) %>
}
    */},
  ],
});
