__DATA({
  model_: 'foam.build.WebApplication',
  id: 'foam.demos.HelloWorldApp',
  controller: 'foam.demos.HelloWorld',
  precompileTemplates: true,
  coreFiles: [
    'firefox',
    'funcName',
    'safari',
    'stdlib',
    'WeakMap',
    'async',
    'parse',
    'event',
    'JSONUtil',
    'XMLUtil',
    'context',
    'JSONParser',
    'TemplateUtil',
    'FOAM',
    'FObject',
    'BootstrapModel',
    'mm1Model',
    'mm2Property',
    'mm3Types',
    'mm4Method',
    'mm5Misc',
    '../js/foam/ui/Window',
    'value',
    'view',
    '../js/foam/ui/FoamTagView',
    'HTMLParser',
    'mlang',
    'mlang2',
    'visitor',
    'messaging',
    'dao',
    'arrayDAO',
    'index',
    'models',
    'oauth',
    'NullModelDAO',
  ]
});
