/**
 * @license
 * Copyright 2017 Google Inc. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

CLASS({
  package: 'demo',
  name: 'ObjcHSource',
  requires: [
    'foam.i18n.TranslationFormatStringParser',
    'foam.util.InlineTrait',
  ],

  methods: [
    function prepModel(model) {
      model = this.InlineTrait.create().inlineTraits(model);

      var filter = function(m) {
        if ( m.labels && m.labels.indexOf('swift') == -1 ) {
          return false;
        }
        return true;
      };

      model.properties = model.properties.filter(filter);
      model.methods = model.methods.filter(filter);
      model.listeners = model.listeners.filter(filter);
      model.messages = model.messages.filter(filter);

      return model;
    },
    function generate(model) {
      return this.objcSource.call(this.prepModel(model), undefined, this);
    },
    function genDetailView(model) {
      return this.detailView.call(this.prepModel(model), undefined, this);
    },
  ],

  templates: [
    function objcSource(_, util) {/*<%
var parser = util.TranslationFormatStringParser.create({stringSymbol: '@'})
var escapeDoubleQuotes = function(s) {
  return s.replace(/"/g, '\\"');
};
var createNsLocalizedString = function(value, hint) {
  parser.value = escapeDoubleQuotes(value);
  parser.translationHint = escapeDoubleQuotes(hint);
  return 'NSLocalizedString("' +
      parser.parsedValue + '", comment: "'+ parser.parsedTranslationHint +'")'
}

%>// Generated by <%= util.model_.id %>.  DO NOT MODIFY BY HAND

TODO: Actually generate a proper .h class.
Class name is: <%= this.swiftClassName %>
Strings:
<% for ( var i = 0, message; message = this.messages[i]; i++) { %>
  <%= message.name %> = <%= createNsLocalizedString(message.value, message.translationHint) %>
<% } %>
*/},
  ],
});
